pkg/infra/Makefile, pkg/infra/go.mod, pkg/infra/go.sum, pkg/infra/logging/logging.go, pkg/infra/main.go
- add logrus to provide logging in JSON format, might be useful for data collection and front end
- add flag to enable CLI arguments support
- add Makefile to help script up workflow
=> Infra logging

.github/workflows/run_game.yaml
Create GitHub action to run game on pull requests.
This new branch was created to remove previous commit left in infra
=> Test performance of agents on push to main

pkg/infra/game/commons/commons.go, pkg/infra/main.go
Minor lints using GolangCI-Lint
=> [infra] Minor lints

pkg/infra/game/agent/agent.go, pkg/infra/game/agent/random.go, pkg/infra/game/stage/fight/fight.go, pkg/infra/game/state/state.go, pkg/infra/main.go
=> [infra] Provide immutable views to agents

Dockerfile, scripts/runDocker.sh
Run `bash scripts/runDocker.sh` in root directory to build and run the game in standardized docker container.
=> [infra] Add Dockerfile and its wrapper script

.gitignore, config.json, frontend/README.md, web/README.md, web/backend/.eslintrc.json, web/backend/package-lock.json, web/backend/package.json, web/backend/src/app.ts, web/backend/src/common/utils.ts, web/backend/src/db/schema/SimResult.ts, web/backend/src/types/global.ts, web/backend/tsconfig.json, web/frontend/.eslintrc.json, web/frontend/index.html, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/App.tsx, web/frontend/src/components/schedule/SubmitModal.tsx, web/frontend/src/components/summary/Leaderboard.tsx, web/frontend/src/main.tsx, web/frontend/src/theme.tsx, web/frontend/src/types/global.ts, web/frontend/src/views/Layout.tsx, web/frontend/src/views/Result.tsx, web/frontend/src/views/Schedule.tsx, web/frontend/src/views/Summary.tsx, web/frontend/src/vite-env.d.ts, web/frontend/tsconfig.json, web/frontend/tsconfig.node.json, web/frontend/vite.config.ts
Just opening this draft PR so people can see the work being done for the web infrastructure.
Work done so far:
- Front end templating
- Front end to back end communication
- Run a game with a given config from the front end
Still to do before Friday 18th:
~~- Set up some sort of DB to store run data (potentially as suggested in #32)~~ Done
=> [web] Initial front-end and back-end

pkg/infra/game/stage/initialise/initialise.go, pkg/infra/game/stages/stages.go, pkg/infra/main.go, pkg/infra/teams/team0/init.go, pkg/infra/teams/team0/team0_agent.go
- Teams can now create their own agent map within their team files for
experimentation.
- Refactor initialise code out of main
- Added an example probabilistic agent in team0 files
=> [Infra] Specialise Initialisation functions for team experiments

pkg/infra/game/math/math.go
fast merge good merge :)))))))
=> simplify maths formula

pkg/infra/game/math/math.go, pkg/infra/game/math/math_test.go
=> add tests to math

pkg/infra/game/example/random.go, pkg/infra/game/stage/initialise/initialise.go, pkg/infra/game/stages/stages.go, pkg/infra/main.go, pkg/infra/teams/team0/init.go
=> [infra] Bugfix on strategy creation

pkg/infra/config/environment_helpers.go, pkg/infra/game/agent/agent.go, pkg/infra/game/agent/base_agent.go, pkg/infra/game/agent/communication.go, pkg/infra/game/commons/commons.go, pkg/infra/game/commons/commons_test.go, pkg/infra/game/decision/decision.go, pkg/infra/game/decision/fight.go, pkg/infra/game/example/random.go, pkg/infra/game/math/math.go, pkg/infra/game/math/math_test.go, pkg/infra/game/message/fight.go, pkg/infra/game/message/message.go, pkg/infra/game/stage/discussion/resolution.go, pkg/infra/game/stage/election/election.go, pkg/infra/game/stage/election/voting.go, pkg/infra/game/stage/fight/fight.go, pkg/infra/game/stage/initialise/initialise.go, pkg/infra/game/stage/loot/loot.go, pkg/infra/game/stages/stages.go, pkg/infra/game/state/view.go, pkg/infra/game/tally/internal/proposal_vote.go, pkg/infra/game/tally/proposal.go, pkg/infra/game/tally/tally.go, pkg/infra/main.go, pkg/infra/main_helper.go, pkg/infra/teams/team0/init.go, pkg/infra/teams/team0/team0_agent.go, pkg/infra/teams/team0/weapon_alloc.go
Handles proposals and adds a tally struct to handle vote counting with impositions on fights.
Fixes #59 partially.
=> [Infra] Add proposals & impositions for fights

pkg/infra/game/agent/agent.go, pkg/infra/game/example/random.go, pkg/infra/game/message/message.go, pkg/infra/game/stage/fight/fight.go
=> [infra] Fix data race

pkg/infra/main_helper.go
=> Fix divide by 0 error when all agents abstain in vote of no confidence

pkg/infra/game/agent/agent.go, pkg/infra/game/example/random.go, pkg/infra/game/message/message.go, pkg/infra/game/tally/proposal.go, pkg/infra/game/tally/tally.go
Bugfix for issue involving proposals
=> Fix proposal management

pkg/infra/game/agent/agent.go, pkg/infra/game/agent/base_agent.go, pkg/infra/game/agent/strategy.go, pkg/infra/game/commons/commons.go, pkg/infra/game/commons/immutablelist.go, pkg/infra/game/decision/result.go, pkg/infra/game/example/random.go, pkg/infra/main.go, pkg/infra/main_helper.go
Gives the agents an opportunity to update their internal state at the end of every level.
Gives agents access to a view of the fight results and vonc result.
=> Let agents update internal state at the end of each round

pkg/infra/game/example/random.go, pkg/infra/game/math/math.go, pkg/infra/game/message/message.go, pkg/infra/game/message/tagged_message.go, pkg/infra/game/stages/stages.go, pkg/infra/main.go
- Adds getters for all parameterised message interfaces
=> Add getters to messages

pkg/infra/game/stage/loot/loot.go, pkg/infra/game/stages/stages.go, pkg/infra/game/state/state.go, pkg/infra/teams/team0/weapon_alloc.go
=> [perf] Spawn goroutines for updates

pkg/infra/game/message/peer.go
Added a separate message type that can be used to send a single int and []string to another agent.
=> [Infra] Add new message format

pkg/infra/game/agent/strategy.go, pkg/infra/game/example/random.go, pkg/infra/game/stage/discussion/resolution.go, pkg/infra/teams/team1/team1_agent.go
Creates randomised auto-allocation by agent choice
=> [infra] fix unlikely bug that leader dies

pkg/infra/game/message/proposal/condition.go, pkg/infra/game/message/proposal/predicate.go
=> [feat] Add recursive grammar for rule conditions

pkg/infra/game/decision/decision.go, pkg/infra/game/stage/discussion/resolution.go, pkg/infra/main.go
Adds defection from the leader's allocation for fight & loot
=> [infra] Enable defection from leader

pkg/infra/game/agent/strategy.go, pkg/infra/game/example/random.go, pkg/infra/game/stage/discussion/resolution.go, pkg/infra/game/tally/proposal.go, pkg/infra/teams/team1/team1_agent.go
=> [feat] Add winning proposals to all agents decision

pkg/infra/game/message/proposal/rule.go
=> Add Getters to Rule fields

pkg/infra/game/state/state.go
Quick fix for the bug @TIE666 found in `BonusDefense()`
https://github.com/SOMAS2022/SOMAS2022/issues/164#issuecomment-1352512459
=> fix AgentState.BonusDefense

pkg/infra/game/math/math.go, pkg/infra/main.go, pkg/infra/main_helper.go
=> added all math equations for loot variables /drop

pkg/infra/game/stage/fight/fight.go
=> [BugFix] Subtract Total Attack/Defense from Stamina

.golangci.yaml
Lots of teams seem to have linting issues with cyclomatic complexities, increased limit to 30
=> [devops] Modified cyclop limit
